global:
  scrape_interval: 4s

scrape_configs:
  - job_name: 'src'
    static_configs:
      - targets: ['src:8000']  

  - job_name: 'loki'
    static_configs:
      - targets: ['loki-service:3100']  

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-service:9090']  
